#!/usr/bin/bash

# do stuff with func
# author: gauron99

# sets FUNC_BIN_PATH to path if successful

# this validates the target dir. Can add various checks: go.mod, git source?
validate_bin(){
	bin=$1
	if [ -f "$bin" ];then
		return 0
	fi
	echo "binary '$bin' doesnt exist, is it a func directory and/or is the binary built?"
	echo ""
	print_help
	return 1
}

# set func alias to a path provided via $1 argument or current directory if $1 is empty
# Will do some basic validation of the directory (needs file called func atleast)
set_func_alias(){
	path=$PWD
	if [ "$1" == "reset" ] || [ "$1" == "default" ];then
		export FUNC_BIN_PATH=
		unalias f 2>/dev/null
		unalias func 2>/dev/null
		echo "unaliased f & func"
		return 0
	fi
	if [ "$1" != "" ];then
		path="$1"
	fi
	#	create a full path for binary (strip any trailing slash, if any)	
	#bin="${path%/}/func"
	bin=$(realpath "$path/func")

	# validate that func is in path, exit if returns false
	validate_bin $bin || return

	# set func
	alias f="$bin"
	alias func="$bin"
	export FUNC_BIN_PATH="$bin"
	
	echo "successfuly set func alias to $bin"
}

# returns 0 on an error and 1 on success
check_help_flag() {
	for arg in "$@"; do
		if [[ "$arg" == "--help" || "$arg" == "-h" ]]; then
			print_help
			return 0
		fi
	done
	return 1
}

print_help() {
	echo "Usage: $0 [OPTIONS]"
	echo "Options:"
	echo "  -h, --help           Sho this help message and exit"
	echo "  reset, default       Reset the 'func' alias to its default state"
	echo "  [PATH]               Set a new 'func' alias pointing to the specified PATH (If not provided, the current directory is used)"

}

main(){
	check_help_flag "$@"	
	if [[ $? -eq 0 ]]; then
		return 0
	fi
	set_func_alias $@
}
# always source this file ('source funchere' or '. funchere')
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This script should be sourced, not executed."
    exit 1
fi
main $@
